version: "3.3"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    networks:
      - django-library
    volumes:
    - ./:/app/
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:17.0-alpine3.20
    container_name: db
    networks:
      - django-library
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

volumes:
  pg_data:

networks:
  django-library:
    external: true
