services:
  db:
    image: postgres:17.0-alpine3.20
    container_name: postgres_labs
    command: -p ${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - labs-web-network
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    container_name: labs_api
    networks:
      - labs-web-network
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db


volumes:
  pgdata:
    name: pgdata
    external: true

networks:
  labs-web-network:
    external: true
