services:
  db:
    image: postgres:17.0-alpine3.20
    container_name: db
    command: -p ${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - labs-web-network
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - labs-web-network
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    container_name: labs_api
    networks:
      - labs-web-network
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db


volumes:
  pgdata:
    name: pgdata
    external: true
  mongo_data:
    name: mongo_data
    external: true

networks:
  labs-web-network:
    external: true
